### ISSUE TITLE
1.2.1 fails to serve .js files with correct content-type

### ISSUE THREAD

**Issue by mikaelfrykholm** [swedenconnect/bankid-saml-idp#260]
We are trying out 1.2.1 there seems to be a problem with the content-type for the generated .js files as in the screenshots below. 
X-Content-Type-Options: nosniff is also set which forces the browser to refuse the file with the wrong content-type. 
1.1.2:
![image](https://github.com/user-attachments/assets/4959c830-7784-4a4d-8ef6-1a87da2558cb)

1.2.1:
![image](https://github.com/user-attachments/assets/c64fe813-ef6d-4538-9c8b-8e149bd5628e)

**Comment by felix-hellman** [comment]
Are both of these from a local environment without any reverse proxy?

**Comment by mikaelfrykholm** [comment]
No, they are both behind a load balancer which is a haproxy.

**Comment by felix-hellman** [comment]
![bankid-content-type](https://github.com/user-attachments/assets/d551408d-89e4-4255-9b49-83f7afbe619a)

I get text/javascript as content type when running with no reverse proxy. (with 1.2.1)
Could you try to reproduce this error in an environment without a reverse proxy to verify that this is an application error?

**Comment by mikaelfrykholm** [comment]
I get a working service when I shut down one frontend. It seems like they serve different index-<id>.js files for each server. The wrong content-type comes from when the server responds with 404.

**Comment by felix-hellman** [comment]
Sounds like the intended behaviour of a 404. I don't really understand what you mean between different frontends. They have different hashes for resources which are computed at build time, so if you load balance between two different builds the result might vary. (I.e. if a client loads version A and tries to load it's resources from version B this will result in a 404 since the hashes doesn't match)

If you agree with me then you can close this issue, otherwise I think I need more information regarding this issue.

**Comment by mikaelfrykholm** [comment]
ah, that solved it. They where running the same version but not the same build. Thanks for helping me chase this goose.
